name: grade exercise 1

on: 
  workflow_dispatch:

jobs: 

  start_job: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by ${{ github.actor }} using ${{ github.event_name }}"  
      - name: retrieve grade
        id: grading
          #if: contains(github.event.issue.labels.*.name, 'excercise1')
        run: |
          echo getting grade from previous job

          #create some variable if it is correct?
          echo "correct=no" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: open issue n+1 when grade is pass
        if: steps.grading.outputs.correct == 'pass'
        run: |
          current_ex=$ISSUE_TITLE
          echo $current_ex
          ex_n=$(echo "$current_ex"|grep -Eo "[0-9]+"|head -n1)
          echo $ex_n
          next_ex="exercise$((ex_n+1))"
          echo $next_ex

          next_file="exercises/${next_ex}.md"
          echo $next_file

          gh issue create --title "$next_ex" --body-file $next_file --repo $GITHUB_REPOSITORY

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: comment on issue if wrong
        if: steps.grading.outputs.correct != 'pass'
        run: gh issue comment $ISSUE --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: Please take a look at your answer



      - name: close original issue
        if: steps.grading.outputs.correct == 'pass'
        run: gh issue close $ISSUE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


