name: grade exercise 1

on: 
  workflow_call:

jobs: 

  start_job: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by ${{ github.actor }} using ${{ github.event_name }}"  

