name: grade exercise 2

on: 
  workflow_dispatch:
    inputs:
      issue_trig:
        required: true
        type: string
      user:
        required: true
        type: string 

jobs: 

  start_job: 
    runs-on: ubuntu-latest
    steps:
      - name: grade ex2
        id: grading
        run: |
          
          #check if repo exist
          found_repo=$(gh repo list "$USER" --json "name" --jq 'any(.[]; .name == "aoc_22")')
          echo $found_repo

          #give correct pass or no if grading went well
          #in this case repo was found
          if [ $found_repo ]
          then
            echo "correct=pass" >> "$GITHUB_OUTPUT"
          else
            echo "correct=no" >> "$GITHUB_OUTPUT"
          fi
        env: 
          USER: ${{ inputs.user }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: open issue n+1 when grade is pass
        if: steps.grading.outputs.correct == 'pass'
        run: |
          #get issue title from html_url
          current_ex=$(gh issue view "$ISSUE" --json title --jq ".title")
          echo $current_ex
          #TODO generalize from reading a file, instead of assuming it is just integer numbers
          ex_n=$(echo "$current_ex"|grep -Eo "[0-9]+"|head -n1)
          echo $ex_n
          next_ex="exercise$((ex_n+1))"
          echo $next_ex

          next_file="exercises/${next_ex}.md"
          echo $next_file

          gh issue create --title "$next_ex" --body-file $next_file --repo $GITHUB_REPOSITORY

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ inputs.issue_trig }}

      - name: comment on issue if wrong
        if: steps.grading.outputs.correct != 'pass'
        run: |
          echo $ISSUE        
          gh issue comment $ISSUE --body "$BODY"  
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: Please take a look at your answer
          ISSUE: ${{ inputs.issue_trig }}


      - name: close original issue
        if: steps.grading.outputs.correct == 'pass'
        run: gh issue close $ISSUE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ inputs.issue_trig }}

