name: grade exercises

on: 
  workflow_call:

jobs: 

  grade_exercise1: 
    if: github.event.issue.title == 'exercise1' 
    uses: ./.github/workflows/exercise1.yml

  # get output and send it as output to caller workflow?     

  grade_exercise2: 
    if: github.event.issue.title == 'exercise2' 
    uses: ./.github/workflows/exercise2.yml 
