# This is a basic workflow to help you get started with Actions

name: Grade when label grade is assign

# Controls when the workflow will run
on:
  # Triggers the workflow when issue is open 
  issues:
    types: [labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  call_grade:
    if: contains(github.event.issue.labels.*.name, 'grade') #change to needs?
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: grade exercise
        run: |
          gh workflow run "$EX_WORKFLOW" -f issue_trig=${{ github.event.issue.html_url }} -f user=${{ github.actor }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EX_WORKFLOW: exercise1.yml





     
