
name: Grade when label grade is assign

on:
  # Triggers the workflow when issue is labeled
  issues:
    types: [labeled]

  # Allows to run workflow manually 
  workflow_dispatch:

jobs:

  call_grade:
    if: contains(github.event.issue.labels.*.name, 'grade') #change to needs?, to better filter?

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
 
      #TODO: get the exercinseN.yml, N, automatically, with current issue       

      - name: grade exercise
        run: |

          CURRENT_ISSUE=${{ github.event.issue.html_url }}
          ISSUE_TITLE=$(gh issue view "$CURRENT_ISSUE" --json title --jq ".title")
          echo $ISSUE_TITLE
          EX_WORKFLOW="$ISSUE_TITLE.yml"
          echo $EX_WORKFLOW
          
          #for now not sending the title using contexts, I can get it in the next workflow with the html_url
          #also see 
          #https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
          gh workflow run "$EX_WORKFLOW" -f issue_trig=${{ github.event.issue.html_url }} -f user=${{ github.actor }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #          EX_WORKFLOW: exercise1.yml





     
