

name: setup new repo

on:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup label and first issues
        run: |


          gh label clone mock-scav-hunt/scav_proto2


          gh issue create --title "$TITLE" --body-file "exercise1.md" --repo $GITHUB_REPOSITORY


        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: exercise1
         
    
           
           

