

name: setup new repo

on:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup label and first issues
        run: |


          #gh repo edit --enable-issues

          gh label clone mock-scav-hunt/scav_proto2


          gh issue create --title "$TITLE" --body "$BODY" --label exercise1 --repo $GITHUB_REPOSITORY

          gh issue create --title "$TITLE2" --body "$BODY2" --label exercise2 --repo $GITHUB_REPOSITORY

        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: Exercise title
          BODY: |
            # Excercise 1
            Some instructions for first problem
          TITLE2: Exercise 2
          BODY2: |
            Some other instructions for second problem

    
           
           

