

name: setup new repo

on:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup label and first issues
        run: |


          gh label clone mock-scav-hunt/scav_proto2

          #open all the exercises as issues 
          for name in $(ls -v exercises)
          do 
            TITLE=$(basename -s ".md" "$name") 
            ISSUE_FILE="exercises/${name}" 
            #read the labels from the comment at bottom of each file
            LABELS=$(tail -n 2 $ISSUE_FILE | head -n 1 | awk -F '[()]' '{print $2}')
            gh issue create --title "$TITLE" --body-file "$ISSUE_FILE" --label "$LABELS"  --repo $GITHUB_REPOSITORY
          done

          #create branch with score
          git checkout -b score
          
          sed -i '/^setup:/s/$/*/' score.md      
 

        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'score.md'
          message: 'update score with setup star'
          new_branch: score
          tag_push: '--set-upstream origin' 
    
           
           

