# This is a basic workflow to help you get started with Actions

name: Open issue when label skip is set in current issue

# Controls when the workflow will run
on:
  # Triggers the workflow when issue is open 
  issues:
    types: [labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(github.event.issue.labels.*.name, 'skip')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}



      - name: open issue with tag2 if issue also had tag1
        if: contains(github.event.issue.labels.*.name, 'exercise1')
        run: |
          echo is running this for label exercise1

          gh issue create --title "$TITLE" --body "$BODY" --label exercise2 --repo $GITHUB_REPOSITORY

        env:      
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: Next Exercise title
          BODY: |
            # Exercise 2
            Some instructions for second problem

                    
          
      - name: close original issue (to be skipped)
        run: gh issue close $ISSUE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}  



      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      
